# -*- coding: utf-8 -*-
"""Lab1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1e_JXoAa4355GGvbNixOW6UGwic7w_Zt7
"""

# hello.py
def main():
    print("Hello, World!")

if __name__ == "__main__":
    main()